### ISSUE TITLE
the code doesnt work either for me

### ISSUE THREAD

**Issue by ItsDaann** [PurpurMC/.github#1]
Related to #384 

The sand duper you are talking about is actually fixed in a different way in Paper. We added a new option for end portal stuff

Set this option to false:

```yaml
blocks.end_portal.safe-teleporting: false
```

We're gotten reports that this option also doesn't work, so get back to us if it works for you or not.

_Originally posted by @BillyGalbreath in https://github.com/PurpurMC/Purpur/issues/392#issuecomment-862388252_

**Comment by encode42** [comment]
This repository is not related to the issue you have created, you're likely looking for [Purpur](https://github.com/PurpurMC/Purpur).
